replicaCount: 1

image:
  repository: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/cmcc-data-publisher
  tag: latest
  pullPolicy: Always

location: circleville

pushGateway:
  host: push-gateway.example.com
  port: 5555

commService:
  host: comm-service.example.com
  rsu: rsu_1

dataTypes:
  - SPAT
  - BSM
  - MAP

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
