replicaCount: 1

image:
  repository: smartcolumbusos/cmcc-data-publisher
  tag: latest
  pullPolicy: Always

location: circleville

pushGateway:
  host: push-gateway.example.com
  port: 5555

commService:
  host: comm-service.example.com
  rsu: rsu_1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
