{{- range $i, $rsu := .Values.commService.rsu }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kapsch-{{ $.Values.location }}-{{ $rsu | replace "_" "-" }}
  labels:
    app.kubernetes.io/name: kapsch-cmcc-publisher-{{ $.Values.location }}-{{ $rsu | replace "_" "-" }}
    helm.sh/chart: kapsch-cmcc-publisher
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kapsch-cmcc-publisher-{{ $.Values.location }}-{{ $rsu | replace "_" "-" }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: kapsch-cmcc-publisher-{{ $.Values.location }}-{{ $rsu | replace "_" "-" }}
            app.kubernetes.io/instance: {{ $.Release.Name }}
        spec:
        {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
        {{- end }}
          restartPolicy: OnFailure
          containers:
          - name: {{ $.Chart.Name }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }} 
            env:
              - name: cmccdatapublisher.udpPublishHost
                value: {{ $.Values.pushGateway.host }}
              - name: cmccdatapublisher.udpPublishPort
                value: {{ quote $.Values.pushGateway.port }}
              - name: cmccdatapublisher.commServicesHost
                value: {{ $.Values.commService.host }}
              - name: cmccdatapublisher.commServicesRsu
                value: {{ $rsu }}
              - name: cmccdatapublisher.commServicesDataTypes
                value: "{{ $.Values.dataTypes | join "," }}"
              - name: cmccdatapublisher.commServicesPassword
                valueFrom:
                  secretKeyRef:
                    name: kapsch-cmcc-publisher-{{ $.Values.location }}
                    key: password
            resources:
              {{- toYaml $.Values.resources | nindent 12 }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
---
{{- end }}