{{- $totalUnits := len .Values.commService.rsu -}}
{{- $maxUnits := default $totalUnits .Values.commService.maxUnits -}}
{{- $sublist := slice .Values.commService.rsu 0 $maxUnits -}}
{{- range $i, $rsu := $sublist }}
{{- $suffix := $rsu | replace "_" "-" | lower -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kapsch-{{ $.Values.location }}-{{ $suffix }}
  labels:
    app.kubernetes.io/name: kapsch-cmcc-publisher-{{ $.Values.location }}-{{ $suffix }}
    helm.sh/chart: kapsch-cmcc-publisher
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  {{ $randomInt := randNumeric 3 | atoi -}}
  schedule: "{{ mod $randomInt 59}} * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kapsch-cmcc-publisher-{{ $.Values.location }}-{{ $suffix }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: kapsch-cmcc-publisher-{{ $.Values.location }}-{{ $suffix }}
            app.kubernetes.io/instance: {{ $.Release.Name }}
        spec:
        {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
        {{- end }}
          restartPolicy: OnFailure
          containers:
          - name: {{ $.Chart.Name }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }} 
            env:
              - name: cmccdatapublisher.udpPublishHost
                value: {{ $.Values.pushGateway.host }}
              - name: cmccdatapublisher.udpPublishPort
                value: {{ quote $.Values.pushGateway.port }}
              - name: cmccdatapublisher.commServicesHost
                value: {{ $.Values.commService.host }}
              - name: cmccdatapublisher.commServicesRsu
                value: {{ $rsu }}
              - name: cmccdatapublisher.commServicesDataTypes
                value: "{{ $.Values.dataTypes | join "," }}"
              - name: cmccdatapublisher.commServicesPassword
                valueFrom:
                  secretKeyRef:
                    name: kapsch-cmcc-publisher-{{ $.Values.location }}
                    key: password
            resources:
              {{- toYaml $.Values.resources | nindent 14 }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
---
{{- end }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ $.Values.location }}-unit-placeholder"
spec:
  replicas: {{ sub $totalUnits $maxUnits }}
  template:
    metadata:
      labels:
        app: "{{ $.Values.location }}-unit-placeholder"
    spec:
      containers:
      - name: "{{ $.Values.location }}-unit-placeholder"
        image: "busybox:latest"
        imagePullPolicy: IfNotPresent
        command: ["tail", "-f", "/dev/null"]
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - cat
            - /dev/null
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /dev/null
          initialDelaySeconds: 5
          periodSeconds: 5
